import hero from "/assets/images/hero.jpeg";

export const heroImg = hero;

import x from "/assets/images/nav-about-x.webp";
import highlightFirstmv from "/assets/videos/highlight-first.mp4";
import highlightSectmv from "/assets/videos/hightlight-third.mp4";
import highlightThirdmv from "/assets/videos/hightlight-sec.mp4";
import highlightFourthmv from "/assets/videos/hightlight-fourth.mp4";
import exploremv from "/assets/videos/explore.mp4";
import framemv from "/assets/videos/presentation.mp4";
import usdc from "/assets/images/usdc.png";
import eth from "/assets/images/eth.png";
import btc from "/assets/images/btc.png";
import egld from "/assets/images/egld.png";
import sol from "/assets/images/sol.png";
import bnb from "/assets/images/bnb.png";
import emerald from "/assets/images/logo-dex.png";
import highlight from "/assets/images/highlight.jpg";
import bag from "/assets/images/bag.svg";
import watch from "/assets/images/watch.svg";
import right from "/assets/images/right.svg";
import replay from "/assets/images/replay.svg";
import play from "/assets/images/play.svg";
import pause from "/assets/images/pause.svg";
import wallet from "/assets/images/wallet.png";
import yellow from "/assets/images/crypto-portofolio.png";
import blue from "/assets/images/blue.jpg";
import white from "/assets/images/white.jpg";
import black from "/assets/images/black.jpg";
import explore1 from "/assets/images/explore1.jpg";
import explore2 from "/assets/images/explore2.jpg";
import frame from "/assets/images/frame.png";
import swap from "/assets/images/swap-stats.png";
export const egldImg = egld;
export const ethImg = eth;
export const btcImg = btc;
export const solImg = sol;
export const bnbImg = bnb;

export const xImg = x;
export const highlightFirstVideo = highlightFirstmv;
export const highlightSecondVideo = highlightSectmv;
export const highlightThirdVideo = highlightThirdmv;
export const highlightFourthVideo = highlightFourthmv;
export const exploreVideo = exploremv;
export const frameVideo = framemv;
export const usdcImg = usdc;
export const swapImg = swap;
export const walletImg = wallet;
export const emeraldImgLogo = emerald;
export const highlightImg = highlight;
export const bagImg = bag;
export const watchImg = watch;
export const rightImg = right;
export const replayImg = replay;
export const playImg = play;
export const pauseImg = pause;

export const yellowImg = yellow;
export const blueImg = blue;
export const whiteImg = white;
export const blackImg = black;
export const explore1Img = explore1;
export const explore2Img = explore2;

export const frameImg = frame;